language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 2.7
      env: TOX_ENV=py27
    - python: pypy
      env: TOX_ENV=pypy
    - python: pypy3
      env: TOX_ENV=pypy3

sudo: false

install:
  - pip install tox
  - pip install python-coveralls codecov

script: tox -e ${TOX_ENV}

after_success:
  - coveralls
  - codecov -e TOX_ENV

cache: pip
